# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.3.1.dev0+g498ff41.d20221115'
__version_tuple__ = version_tuple = (0, 3, 1, 'dev0', 'g498ff41.d20221115')
